version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused

  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (*os.File).Close

formatters:
  enable:
    - gofmt
